<?php
	$result_register=mysqli_fetch_array($sql_register);
	$total_registro=$result_register['total_registro'];
	$por_pagina=10;
	if(empty($_REQUEST['pagina'])){
		$pagina=1;
	}else{
		$pagina=$_REQUEST['pagina'];
	}
	$desde=($pagina-1)*$por_pagina;
	$total_paginas=ceil($total_registro/$por_pagina);
?>